import { create } from "zustand";

const useFormStore = create((set) => ({
  step: 1,
  tripName: "",
  tripOrigin: "",
  tripDestination: "",
  length: "",
  width: "",
  height: "",
  weight: "",
  tripOriginLat: null,
  tripOriginLon: null,
  tripDestinationLat: null,
  tripDestinationLon: null,
  lengthInches: 0,
  widthInches: 0,
  heightInches: 0,
  calculatedPrice: null,
  inputValue: "",
  options: [],
  setStep: (step) => set({ step }),
  setTripName: (name) => set({ tripName: name }),
  setTripOrigin: (origin) => set({ tripOrigin: origin }),
  setTripDestination: (destination) => set({ tripDestination: destination }),
  setLength: (length) => set({ length }),
  setWidth: (width) => set({ width }),
  setHeight: (height) => set({ height }),
  setWeight: (weight) => set({ weight }),
  setTripOriginLat: (lat) => set({ tripOriginLat: lat }),
  setTripOriginLon: (lon) => set({ tripOriginLon: lon }),
  setTripDestinationLat: (lat) => set({ tripDestinationLat: lat }),
  setTripDestinationLon: (lon) => set({ tripDestinationLon: lon }),
  setLengthInches: (inches) => set({ lengthInches: inches }),
  setWidthInches: (inches) => set({ widthInches: inches }),
  setHeightInches: (inches) => set({ heightInches: inches }),
  setCalculatedPrice: (price) => set({ calculatedPrice: price }),
  setInputValue: (value) => set({ inputValue: value }),
  setOptions: (options) => set({ options: options }),
  resetForm: () =>
    set({
      step: 1,
      tripName: "",
      tripOrigin: "",
      tripDestination: "",
      length: "",
      width: "",
      height: "",
      weight: "",
      tripOriginLat: null,
      tripOriginLon: null,
      tripDestinationLat: null,
      tripDestinationLon: null,
      lengthInches: 0,
      widthInches: 0,
      heightInches: 0,
      calculatedPrice: null,
      inputValue: "",
      options: [],
    }),
}));

export default useFormStore;
